rabbitMQ:              
  username: "root"             
  password: "password"    
  addr: "172.16.84.66"      
  port: 30672      
  routingKey: "thing.issue.#"        
  exchange: "mqtt"  
  exchangeType: "topic"    
  reliable: true             
  queue: "device-issue"   
  consumerTag: "device-issue"
mqtt:
  addr: "172.16.84.66"
  port: 31883